### ISSUE TITLE
Create CDR bank aggregator TPP

### ISSUE THREAD

**Issue by shprink** [OpenBankingToolkit/consumer-data-right-reference-implementation#69]
Mockups: https://balsamiq.cloud/spnlzmh/poc1jk9/r0C6F

* [x] App scaffolding
* [x] App pages
* [x] App data handling + cache
* [x] Server scaffolding
* [x] Server TPP TLS connection
* [x] Server Auth
* [x] Server Consent/oauth2
* [x] Server get Accounts
* [x] Server get Transactions
* [x] Server get balance
* [x] Access Token expiration logic
* [x] Docker-compose
* [x] Code base cleanup
* [x] Docs

**Comment by BohoCode** [comment]
@shprink can this be closed now?
